name: Sojourning Settler
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-55772232-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.0625
  lightness: 0.5479804934002459
  saturation: 0.9817065438255668
  rhythmicContrast: 0.2867066883482039
purpose: []
